version: "3"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - webnet
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      nproc: 3000
      nofile: 65536
      memlock: -1
  difido:
    image: itaiag/difido:difido
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
